name: cs7643music

channels:
  - pytorch
  - defaults
dependencies:
  - python>=3.7
  - ipython>=3.2.1
  - jupyter
  - ipykernel
  - nb_conda
  - matplotlib>=1.5.1
  - scikit-learn=0.20.0
  - numpy>=1.9.1
  - scipy>=0.14.1
  - mkl
  - pytorch
  - torchvision
  - pip
  - pip:
    - mido=1.2.9